In [18]:
train_file_path=r"C:\Users\Brothers\Inueron_first\fsds2020\Machine-Learning-Projrect\housing\artifact\data_ingestion\2022-09-13-16-03-48\raw_data\housing.csv"

In [19]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

c:\Users\Brothers\Inueron_first\fsds2020\Machine-Learning-Projrect\venv\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [20]:
df=pd.read_csv(train_file_path)

In [21]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [22]:
df.shape

(20640, 10)

In [23]:
x,y= df.drop(columns=['median_house_value']),df['median_house_value']

In [24]:
x

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income ocean_proximity  
0           322.0       126.0         8.3252        NEAR BAY  
1          2401.0      1138.0         8.3014        NEAR BAY  
2           496.0       177.0         7.2574        NEAR BAY  
3           558.0       219.0         5.6431        NEAR BAY  
4           565.0       259.0         3.8462        NEAR BAY  
...           ...         ...            ...             ...  
20635       845.0       330.0         1.5603          INLAND  
20636       356.0       114.0         2.5568          INLAND  
20637      1007.0       433.0         1.7000          INLAND  
20638       741.0       349.0         1.8672          INLAND  
20639      1387.0       530.0         2.3886          INLAND  

[20640 rows x 9 columns]

In [25]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...   
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [26]:
x.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [27]:
numerical_feature=x.drop(columns=['ocean_proximity'],axis=1)

In [28]:
from sklearn.impute import SimpleImputer

In [29]:
simple_imputer= SimpleImputer(strategy='median')

In [30]:
simple_imputer.fit_transform(numerical_feature)

array([[-1.2223e+02,  3.7880e+01,  4.1000e+01, ...,  3.2200e+02,
         1.2600e+02,  8.3252e+00],
       [-1.2222e+02,  3.7860e+01,  2.1000e+01, ...,  2.4010e+03,
         1.1380e+03,  8.3014e+00],
       [-1.2224e+02,  3.7850e+01,  5.2000e+01, ...,  4.9600e+02,
         1.7700e+02,  7.2574e+00],
       ...,
       [-1.2122e+02,  3.9430e+01,  1.7000e+01, ...,  1.0070e+03,
         4.3300e+02,  1.7000e+00],
       [-1.2132e+02,  3.9430e+01,  1.8000e+01, ...,  7.4100e+02,
         3.4900e+02,  1.8672e+00],
       [-1.2124e+02,  3.9370e+01,  1.6000e+01, ...,  1.3870e+03,
         5.3000e+02,  2.3886e+00]])

In [31]:
df=simple_imputer.transform(numerical_feature)

In [32]:
simple_imputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [33]:
simple_imputer.statistics_

array([-118.49  ,   34.26  ,   29.    , 2127.    ,  435.    , 1166.    ,
        409.    ,    3.5348])

In [34]:
x.longitude.median()

-118.49

In [35]:
x.latitude.median()

34.26

In [36]:
x.ocean_proximity.value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [37]:
from sklearn.base import BaseEstimator,TransformerMixin

In [38]:
simple_imputer=SimpleImputer(strategy='most_frequent')

In [39]:
for idx,column in enumerate(x.columns):
    print(idx,column)

0 longitude
1 latitude
2 housing_median_age
3 total_rooms
4 total_bedrooms
5 population
6 households
7 median_income
8 ocean_proximity


In [64]:
COLUMN_TOTAL_ROOMS="total_rooms"
COLUMN_POPULATION="population"
COLUMN_HOUSEHOLDS="households"
COLUMN_TOTAL_BEDROOM="total_bedrooms"

class FeatureGenerator(BaseEstimator,TransformerMixin):
    
    def __init__(self, add_bedrooms_per_room=True,
            total_rooms_ix=3,
            population_ix=5,
            households_ix=6,
            total_bedrooms_ix=4,columns=None):
    
        try:
            self.columns=columns
            if self.columns is not None:
                total_rooms_ix=self.columns.index(COLUMN_TOTAL_ROOMS)
                population_ix=self.columns.index(COLUMN_POPULATION)
                households_ix=self.columns.index(COLUMN_HOUSEHOLDS)
                total_bedrooms_ix=self.columns.index(COLUMN_TOTAL_BEDROOM)

            self.add_bedrooms_per_room=add_bedrooms_per_room
            self.total_rooms_ix=total_rooms_ix
            self.population_ix=population_ix
            self.households_ix= households_ix
            self.total_bedrooms_ix=total_bedrooms_ix
        except Exception as e:
            raise e

def fit(self,x,y=None):
    return self
    

def transform(self,x,y=None):
    try:
        rooms_per_household=x[:,self.total_rooms_ix] / \
                            x[:, self. households_ix] 
        population_per_household=x[:, self.population_ix] / \
                                 x[:, self. households_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room=x[:,self.total_bedrooms_ix] / \
                              x[:,self.total_rooms_ix]
            generated_feature= np.c_[
                x,rooms_per_household,population_per_household,bedrooms_per_room]
        else:
            generated_feature= np.c_[
                x,rooms_per_household,population_per_household]
        return generated_feature

    except Exception as e :
        raise e

            



In [65]:
import numpy as np

In [66]:
arr1=np.arange(12)
arr2=np.arange(12)

In [67]:
np.c_[arr1,arr2]

array([[ 0,  0],
       [ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [ 4,  4],
       [ 5,  5],
       [ 6,  6],
       [ 7,  7],
       [ 8,  8],
       [ 9,  9],
       [10, 10],
       [11, 11]])

In [68]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [69]:
from sklearn.preprocessing import StandardScaler

In [70]:
from sklearn.preprocessing import OneHotEncoder

In [71]:
cat_pipeline= Pipeline(steps=[
    ('imputer',SimpleImputer(strategy="most_frequent")),
    ('OneHotEncoder',OneHotEncoder()),
    ('scaling',StandardScaler()) 
])

In [ ]:
num_pipeline= Pipeline(steps=[
    ('imputer',SimpleImputer(strategy="median")),
    ('feature_generator',FeatureGenerator()),
    ('scaling',StandardScaler()) 
])